services:
  openChat:
    image: showjimzc/openchat:latest
    pull_policy: always
    container_name: openChat
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/jerry/setting:/app/setting
      - /home/jerry/workDir:/app/workDir
    restart: always
    ports:
      - 8504:8501
